#!/bin/bash
dlwk=$((10#`date +%j` - 7))
mv /etc/pacman.d/mirrorlist{,-$[10#`date +%j`]} || return 1
reflector -a 24 -l 15 -f 15 --save /etc/pacman.d/mirrorlist || return 1
rm /etc/pacman.d/mirrorlist-$dlwk
pacman -Sy

