#!/bin/bash
dlwk=$((10#`date +%j` - 7))
mv /etc/pacman.d/mirrorlist{,-$[10#`date +%j`]} || return 1
reflector -l 10 -h 6 -r -o /etc/pacman.d/mirrorlist || return 1
rm /etc/pacman.d/mirrorlist-$dlwk
pacman -Sy

